import { createFileRoute } from "@tanstack/react-router";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

import { type CatalogItem, useLocalCrm } from "@/lib/local-crm";

export const Route = createFileRoute("/_auth/catalog")({ component: CatalogPage });
const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });

function CatalogPage() {
  const { catalog, saveCatalogItem, deleteCatalogItem } = useLocalCrm();
  const [editing, setEditing] = useState<CatalogItem | null>(null);
  const [creating, setCreating] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const item: CatalogItem = { id: editing?.id ?? crypto.randomUUID(), name: String(data.get("name") ?? "").trim(), description: String(data.get("description") ?? "").trim(), category: String(data.get("category") ?? "Prestation").trim(), unit: String(data.get("unit") ?? "forfait").trim(), unitPriceCents: Math.round(Number(data.get("price") ?? 0) * 100), vatRate: Number(data.get("vatRate") ?? 10), active: true }; if (!item.name) return; await saveCatalogItem(item); setEditing(null); setCreating(false); toast.success("Article enregistré"); };
  return <div className="space-y-6"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.16em] text-[#7d6f67] uppercase">Base de chiffrage</p><h1 className="mt-1 font-serif text-4xl font-bold">Catalogue</h1><p className="mt-2 text-sm text-stone-600">Les prestations, options et tarifs réutilisables dans les devis.</p></div><button onClick={() => { setEditing(null); setCreating(true); }} className="inline-flex items-center gap-2 rounded-md bg-[#650d1c] px-4 py-2.5 text-sm font-bold text-white"><Plus className="size-4" />Ajouter un article</button></section>{(creating || editing) && <CatalogForm item={editing} onCancel={() => { setEditing(null); setCreating(false); }} onSubmit={submit} />}<section className="overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm">{catalog.length === 0 ? <div className="p-10 text-center"><p className="font-serif text-2xl font-bold">Le catalogue est vide</p><p className="mt-2 text-sm text-stone-500">Ajoute tes formules, options, livraisons et prestations pour les intégrer aux devis.</p></div> : <div className="divide-y divide-stone-100">{catalog.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="flex gap-2"><span className="rounded-full bg-[#f5ecee] px-2 py-0.5 text-xs font-bold text-[#8b1629]">{item.category}</span><span className="text-xs text-stone-400">{item.unit}</span></div><h2 className="mt-2 font-semibold">{item.name}</h2><p className="mt-1 text-sm text-stone-500">{item.description || "Sans description"}</p></div><div className="flex items-center gap-4"><p className="font-serif text-xl font-bold">{euro.format(item.unitPriceCents / 100)} <span className="text-xs font-sans font-normal text-stone-500">HT · TVA {item.vatRate} %</span></p><button onClick={() => setEditing(item)} aria-label={`Modifier ${item.name}`} className="text-[#8b1629]"><Pencil className="size-4" /></button><button onClick={() => deleteCatalogItem(item.id)} aria-label={`Supprimer ${item.name}`} className="text-stone-400 hover:text-[#8b1629]"><Trash2 className="size-4" /></button></div></article>)}</div>}</section></div>;
}
function CatalogForm({ item, onCancel, onSubmit }: { item: CatalogItem | null; onCancel: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit} className="grid gap-4 rounded-xl border border-stone-200 bg-white p-6 shadow-sm md:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Nom<input required name="name" defaultValue={item?.name} className="input" /></label><label className="grid gap-1 text-sm font-semibold">Catégorie<input name="category" defaultValue={item?.category ?? "Prestation"} className="input" /></label><label className="grid gap-1 text-sm font-semibold">Description<textarea name="description" defaultValue={item?.description} className="input min-h-20" /></label><div className="grid grid-cols-3 gap-3"><label className="grid gap-1 text-sm font-semibold">Unité<input name="unit" defaultValue={item?.unit ?? "forfait"} className="input" /></label><label className="grid gap-1 text-sm font-semibold">Prix HT<input required min="0" step="0.01" name="price" type="number" defaultValue={item ? item.unitPriceCents / 100 : ""} className="input" /></label><label className="grid gap-1 text-sm font-semibold">TVA<select name="vatRate" defaultValue={item?.vatRate ?? 10} className="input"><option value="0">0 %</option><option value="5.5">5,5 %</option><option value="10">10 %</option><option value="20">20 %</option></select></label></div><div className="flex items-end justify-end gap-2 md:col-span-2"><button type="button" onClick={onCancel} className="px-3 py-2 text-sm font-bold">Annuler</button><button className="rounded-md bg-[#650d1c] px-4 py-2 text-sm font-bold text-white">Enregistrer l’article</button></div></form>; }
