import { createFileRoute } from "@tanstack/react-router";
import { useAction, useMutation, useQuery } from "convex/react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { api } from "@ERPTrisThom/backend/convex/_generated/api";
import type { Id } from "@ERPTrisThom/backend/convex/_generated/dataModel";
import { cleanInboxBody, parse1001Request } from "@/domain/inbox-display";

export const Route = createFileRoute("/_auth/inbox")({ component: InboxPage });
type PlanAction = { type: string; label: string; confidence?: string; reason?: string; data: Record<string, unknown>; selected: boolean };
type Entry = { _id: string; senderName?: string; senderEmail?: string; subject?: string; body?: string; receivedAt?: number; createdAt: number; analysis?: { status: string; summary?: string; messageType?: string; plan?: string; error?: string } | null };
const button = "rounded-lg border px-3 py-2 text-sm font-semibold";

function InboxPage() {
  const [processed, setProcessed] = useState(false); const [raw, setRaw] = useState<string>(); const [create, setCreate] = useState<Entry>(); const [attach, setAttach] = useState<Entry>(); const [review, setReview] = useState<Entry>();
  const rows = useQuery(api.inboxEntries.list, { processed }) as Entry[] | undefined;
  const candidates = useQuery(api.inboxEntries.candidates, {});
  const ignore = useMutation(api.inboxEntries.ignore); const attachEntry = useMutation(api.inboxEntries.attach); const createRequest = useMutation(api.inboxEntries.createRequest); const applyPlan = useMutation(api.inboxEntries.applyPlan); const analyze = useAction(api.inboxAgent.analyze);
  const date = useMemo(() => new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }), []);
  const ignoreRow = async (entry: Entry) => { await ignore({ inboxMessageId: entry._id as Id<"inboxMessages"> }); toast.success("Entrée ignorée"); };
  return <div className="space-y-5"><div><h1 className="font-serif text-4xl font-bold">Entrées</h1><p className="text-sm text-stone-600">L’agent propose ; vous décidez.</p></div>
    <div className="flex gap-2"><button onClick={() => setProcessed(false)} className={!processed ? "rounded-full bg-[#650d1c] px-3 py-1.5 text-sm font-bold text-white" : "rounded-full bg-stone-100 px-3 py-1.5 text-sm font-bold"}>À traiter</button><button onClick={() => setProcessed(true)} className={processed ? "rounded-full bg-[#650d1c] px-3 py-1.5 text-sm font-bold text-white" : "rounded-full bg-stone-100 px-3 py-1.5 text-sm font-bold"}>Historique</button></div>
    {rows?.length === 0 ? <p>Tout est traité ✓</p> : <section className="overflow-hidden rounded-xl border bg-white">{rows?.map(entry => <article key={entry._id} className="space-y-3 border-b p-5"><div><strong>{entry.senderName || entry.senderEmail || "Expéditeur inconnu"}</strong><p className="text-sm text-stone-500">{entry.subject || "Sans objet"} · {date.format(entry.receivedAt ?? entry.createdAt)}</p><p className="mt-2 whitespace-pre-wrap text-sm">{cleanInboxBody(entry.body)}</p></div>{!processed && <>
      <Analysis entry={entry} analyze={() => void analyze({ inboxMessageId: entry._id as Id<"inboxMessages"> }).catch(error => toast.error(error instanceof Error ? error.message : "Analyse impossible"))} examine={() => setReview(entry)} />
      <div className="flex flex-wrap gap-2"><button onClick={() => setCreate(entry)} className="rounded-lg bg-[#650d1c] px-3 py-2 text-sm font-bold text-white">Créer un dossier</button><button onClick={() => setAttach(entry)} className={button}>Rattacher à un dossier</button><button onClick={() => void ignoreRow(entry)} className={button}>Ignorer</button><button onClick={() => setRaw(raw === entry._id ? undefined : entry._id)} className="px-2 text-sm font-semibold text-[#8b1629]">Voir l’e-mail complet</button></div></>}
      {raw === entry._id && <pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg bg-stone-50 p-3 text-xs">{entry.body || ""}</pre>}</article>)}</section>}
    {create && <CreateForm entry={create} close={() => setCreate(undefined)} save={createRequest} />}{attach && <AttachForm entry={attach} candidates={candidates ?? []} close={() => setAttach(undefined)} save={attachEntry} />}{review && <Review entry={review} close={() => setReview(undefined)} apply={applyPlan} />}
  </div>;
}

function Analysis({ entry, analyze, examine }: { entry: Entry; analyze: () => void; examine: () => void }) {
  const plan = parsePlan(entry.analysis?.plan); if (!entry.analysis || entry.analysis.status === "analysis_failed") return <div className="rounded-lg bg-stone-50 p-3 text-sm"><p>{entry.analysis?.error ? "Analyse indisponible : les actions manuelles restent disponibles." : "Analyse IA non lancée."}</p><button className="mt-2 font-bold text-[#8b1629]" onClick={analyze}>{entry.analysis ? "Relancer l’analyse" : "Analyser l’entrée"}</button></div>;
  if (entry.analysis.status === "pending_analysis") return <div className="rounded-lg bg-stone-50 p-3 text-sm">Analyse en cours…</div>;
  return <div className="rounded-lg border border-[#e8d5d8] bg-[#fffafa] p-3 text-sm"><p className="font-bold">Résumé IA</p><p>{entry.analysis.summary}</p><p className="mt-1 text-stone-600">{entry.analysis.messageType} · {plan.length} action{plan.length > 1 ? "s" : ""} proposée{plan.length > 1 ? "s" : ""}</p><button className="mt-2 font-bold text-[#8b1629]" onClick={examine}>Examiner la proposition</button></div>;
}

function parsePlan(raw?: string): PlanAction[] { try { const value = JSON.parse(raw || "{}"); return Array.isArray(value.actions) ? value.actions.map((a: Omit<PlanAction, "selected">) => ({ ...a, selected: true })) : []; } catch { return []; } }
function CreateForm({ entry, close, save }: { entry: Entry; close: () => void; save: ReturnType<typeof useMutation> }) { const p = parse1001Request(entry.senderEmail, entry.subject, entry.body); return <Modal title="Créer le dossier" close={close}><form onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); await save({ inboxMessageId: entry._id as Id<"inboxMessages">, contactName: String(data.get("name")), contactEmail: String(data.get("email")) || undefined, contactPhone: String(data.get("phone")) || undefined, eventType: String(data.get("type")) || undefined, eventDate: data.get("date") ? new Date(`${data.get("date")}T12:00:00`).getTime() : undefined, eventAddress: String(data.get("address")) || undefined, guestCount: data.get("guests") ? Number(data.get("guests")) : undefined, budgetPerPersonCents: data.get("budget") ? Number(data.get("budget")) * 100 : undefined, specialNeeds: String(data.get("notes")) || undefined }); toast.success("Dossier créé"); close(); }} className="grid gap-3">{[["name", "Nom", p?.name || entry.senderName || ""], ["email", "E-mail", p?.email || entry.senderEmail || ""], ["phone", "Téléphone", p?.phone || ""], ["type", "Prestation", p?.eventType || ""], ["date", "Date", p?.eventDate?.split("/").reverse().join("-") || ""], ["address", "Lieu", p?.venue || ""], ["guests", "Personnes", p?.guests || ""], ["budget", "Budget / personne", p?.budgetPerPerson || ""], ["notes", "Format / notes", [p?.cateringMode, ...(p?.options || []), p?.customerMessage].filter(Boolean).join(" · ")]].map(([name, label, value]) => <label key={name} className="grid gap-1 text-sm font-semibold">{label}<input className="input" name={name} defaultValue={value} type={name === "date" ? "date" : name === "guests" || name === "budget" ? "number" : "text"} /></label>)}<div className="flex justify-end gap-2"><button type="button" onClick={close}>Annuler</button><button className="rounded bg-[#650d1c] px-3 py-2 font-bold text-white">Créer le dossier</button></div></form></Modal>; }
function AttachForm({ entry, candidates, close, save }: { entry: Entry; candidates: Array<{ _id: string; label: string }>; close: () => void; save: ReturnType<typeof useMutation> }) { return <Modal title="Rattacher à un dossier" close={close}><form onSubmit={async event => { event.preventDefault(); const requestId = String(new FormData(event.currentTarget).get("requestId")); if (!requestId) return; await save({ inboxMessageId: entry._id as Id<"inboxMessages">, requestId: requestId as Id<"requests"> }); toast.success("E-mail rattaché"); close(); }} className="grid gap-4"><select className="input" name="requestId" defaultValue=""><option value="" disabled>Choisir un dossier</option>{candidates.map(candidate => <option key={candidate._id} value={candidate._id}>{candidate.label}</option>)}</select><div className="flex justify-end gap-2"><button type="button" onClick={close}>Annuler</button><button className="rounded bg-[#650d1c] px-3 py-2 font-bold text-white">Rattacher</button></div></form></Modal>; }
function Review({ entry, close, apply }: { entry: Entry; close: () => void; apply: ReturnType<typeof useMutation> }) { const [actions, setActions] = useState(parsePlan(entry.analysis?.plan)); const selected = actions.filter(action => action.selected).length; return <Modal title="Examiner la proposition" close={close} wide><div className="grid gap-5 md:grid-cols-2"><div><p className="font-semibold">Mail client</p><p className="mt-2 whitespace-pre-wrap text-sm">{cleanInboxBody(entry.body)}</p></div><div className="space-y-3"><p className="text-sm">Cochez les actions à appliquer. Les données JSON peuvent être ajustées avant validation.</p>{actions.map((action, index) => <div key={index} className="rounded-lg border p-3"><label className="flex gap-2 font-semibold"><input type="checkbox" checked={action.selected} onChange={event => setActions(actions.map((value, i) => i === index ? { ...value, selected: event.target.checked } : value))} />{action.label}</label><p className="mt-1 text-xs text-stone-600">{action.reason} · confiance {action.confidence}</p><textarea className="input mt-2 min-h-20 font-mono text-xs" value={JSON.stringify(action.data, null, 2)} onChange={event => { try { const data = JSON.parse(event.target.value); setActions(actions.map((value, i) => i === index ? { ...value, data } : value)); } catch { /* retain last valid values */ } }} /></div>)}<div className="flex gap-2"><button className={button} onClick={() => setActions(actions.map(action => ({ ...action, selected: true })))}>Tout sélectionner</button><button className={button} onClick={() => setActions(actions.map(action => ({ ...action, selected: false })))}>Tout désélectionner</button></div><button disabled={!selected} onClick={async () => { await apply({ inboxMessageId: entry._id as Id<"inboxMessages">, actions }); toast.success(`${selected} action${selected > 1 ? "s" : ""} appliquée${selected > 1 ? "s" : ""}`); close(); }} className="rounded bg-[#650d1c] px-3 py-2 font-bold text-white disabled:opacity-50">Appliquer {selected} action{selected > 1 ? "s" : ""}</button></div></div></Modal>; }
function Modal({ title, close, children, wide = false }: { title: string; close: () => void; children: React.ReactNode; wide?: boolean }) { return <div className="fixed inset-0 z-50 overflow-auto bg-black/30 p-4"><div className={`mx-auto mt-10 rounded-xl bg-white p-6 ${wide ? "max-w-5xl" : "max-w-xl"}`}><div className="mb-4 flex items-center justify-between"><h2 className="font-serif text-2xl font-bold">{title}</h2><button onClick={close}>Fermer</button></div>{children}</div></div>; }
