import { useMutation, useQuery } from "convex/react";
import { useState } from "react";
import { toast } from "sonner";
import { api } from "@ERPTrisThom/backend/convex/_generated/api";
import type { Id } from "@ERPTrisThom/backend/convex/_generated/dataModel";
import type { LocalRequest } from "@/lib/local-crm";

export function RequestEvents({ request }: { request: LocalRequest }) {
  const review = useMutation(api.crm.reviewLegacyServices);
  const archivedEvents = useQuery(api.requestEvents.list, { requestId: request._id as Id<"requests"> });
  const [retained, setRetained] = useState("");
  const [decision, setDecision] = useState("");
  const [confirmed, setConfirmed] = useState(false);
  const [busy, setBusy] = useState(false);
  if (!request.legacyEvents?.length) return archivedEvents?.length ? <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">Archives des prestations avant reprise</summary>{archivedEvents.map(event => <p key={event._id} className="mt-2 text-sm">{event.label} · {event.date == null ? "Sans date" : new Date(event.date).toLocaleDateString("fr-FR")} · {event.address} · {event.guestCount ?? "?"} personnes · {event.status}{event.notes ? " · " + event.notes : ""}</p>)}</details> : null;
  return <section className="rounded-xl border border-amber-300 bg-amber-50 p-5"><h2 className="font-serif text-2xl font-bold">Anciennes prestations à reprendre</h2><p className="mt-3 text-sm">Ce dossier contient plusieurs sources de données. Choisissez la prestation qui conservera tous les devis, achats, notes et échanges existants. Les autres prestations deviendront des dossiers nouveaux, sans devis ni montant. Les anciennes lignes seront conservées pour consultation.</p><p className="mt-2 text-sm font-semibold">Si le devis couvre plusieurs dates, corrigez d’abord sa répartition avec le client. Ne validez pas cette reprise tant que cette attribution n’est pas décidée.</p><form className="mt-4 space-y-3" onSubmit={async event => { event.preventDefault(); if (busy || !confirmed) return; setBusy(true); try { await review({ requestId: request._id as Id<"requests">, retainedEventId: retained as Id<"requestEvents">, expectedUpdatedAt: request.updatedAt, financialDecision: decision }); toast.success("Reprise enregistrée sans duplication des montants"); } catch (error) { toast.error(error instanceof Error ? error.message : "Reprise impossible"); } finally { setBusy(false); } }}><fieldset disabled={busy} className="space-y-3">{request.legacyEvents.map(event => <label key={event._id} className="flex gap-3 rounded border border-amber-200 bg-white p-3 text-sm"><input required type="radio" name="retained" value={event._id} checked={retained === event._id} onChange={() => setRetained(event._id)} /><span><strong>{event.label}</strong> · {event.date == null ? "Date à préciser" : new Date(event.date).toLocaleDateString("fr-FR")} · {event.guestCount ?? "?"} personnes · {event.address || "Lieu à préciser"} · {event.status}</span></label>)}<label className="grid gap-1 text-sm font-semibold">Décision sur le devis et les achats<textarea required minLength={10} className="input" value={decision} onChange={event => setDecision(event.target.value)} placeholder="Expliquez pourquoi ces documents sont attribués à la prestation sélectionnée." /></label><label className="flex gap-2 text-sm"><input required type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />J’ai vérifié l’attribution des documents ; les autres dossiers repartiront sans devis ni achats.</label><button disabled={!retained || !confirmed || decision.trim().length < 10 || busy} className="rounded bg-[#650d1c] px-3 py-2 font-bold text-white disabled:opacity-50">Valider la reprise de ce dossier</button></fieldset></form></section>;
}
