// @ts-expect-error Bun supplies this module when running `bun test`.
import { expect, test } from "bun:test";
import { matchesRequestFilters, matchesRequestSearch, matchesRequestView, needsActionToday, normalizeRequestSearch, sortRequests } from "./request-list";
const request: any = { _id: "r", contactName: "Élodie Martin", organizationName: "Maison Brûlée", contactEmail: "elodie@maison.fr", contactPhone: "0612345678", eventType: "Cocktail", eventAddress: "Paris", status: "qualifie", missingInformation: [], followUps: [], createdAt: 1, updatedAt: 1 };
test("search covers client, company, email, phone, quote and accents", () => { for (const value of ["elodie", "maison brulee", "elodie@", "123456", "D-2026"]) expect(matchesRequestSearch(request, value, { quoteNumber: "D-2026-001" } as any)).toBe(true); expect(normalizeRequestSearch("Élodie")).toBe("elodie"); });
test("today actions only use due follow-ups and next actions", () => { const now = new Date(2026, 6, 22, 10).getTime(); expect(needsActionToday({ ...request, missingInformation: ["Date"] }, now)).toBe(false); expect(needsActionToday({ ...request, nextActionAt: now }, now)).toBe(true); expect(needsActionToday({ ...request, followUps: [{ dueAt: now, completedAt: undefined }] }, now)).toBe(true); });
test("sort by next action", () => expect(sortRequests([{ ...request, _id: "late", nextActionAt: 20 }, { ...request, _id: "early", nextActionAt: 10 }], "nextAction", 0).map((item) => item._id)).toEqual(["early", "late"]));
test("filters active and historical requests with normalized legacy statuses", () => { expect(matchesRequestView({ ...request, status: "qualifie" }, "active")).toBe(true); expect(matchesRequestView({ ...request, status: "termine" }, "active")).toBe(false); expect(matchesRequestView({ ...request, status: "termine" }, "history")).toBe(true); });
test("sorts event dates in both directions", () => { const values = [{ ...request, _id: "late", eventDate: 20 }, { ...request, _id: "early", eventDate: 10 }]; expect(sortRequests(values, "eventDate", 0).map((item) => item._id)).toEqual(["early", "late"]); expect(sortRequests(values, "eventDateDesc", 0).map((item) => item._id)).toEqual(["late", "early"]); });
test("combines multiple status and source filters", () => { expect(matchesRequestFilters({ ...request, status: "nouveau", source: "email" }, new Set(["nouveau", "devis_a_preparer"]), new Set(["email"]))).toBe(true); expect(matchesRequestFilters({ ...request, status: "accepte", source: "email" }, new Set(["nouveau", "devis_a_preparer"]), new Set(["email"]))).toBe(false); expect(matchesRequestFilters({ ...request, status: "nouveau", source: "manuel" }, new Set(["nouveau"]), new Set(["email"]))).toBe(false); });
