import { v } from "convex/values";
import { authComponent } from "./auth";
import { mutation, query } from "./_generated/server";
async function user(ctx: Parameters<typeof authComponent.safeGetAuthUser>[0]) { if (!await authComponent.safeGetAuthUser(ctx)) throw new Error("Vous devez être connecté."); }
export const list = query({ args: { processed: v.boolean() }, handler: async (ctx, args) => { await user(ctx); const rows = await ctx.db.query("inboxMessages").take(500); return rows.filter(row => args.processed ? row.reviewStatus !== "pending" : row.reviewStatus === "pending").sort((a,b)=>(b.receivedAt ?? b.createdAt)-(a.receivedAt ?? a.createdAt)); } });
export const pendingCount = query({ args: {}, handler: async (ctx) => { await user(ctx); const rows = await ctx.db.query("inboxMessages").take(10_000); return rows.filter(row => row.reviewStatus === "pending").length; } });
export const ignore = mutation({ args: { inboxMessageId: v.id("inboxMessages") }, handler: async (ctx,args) => { await user(ctx); const row=await ctx.db.get(args.inboxMessageId); if(!row) throw new Error("Entrée introuvable."); await ctx.db.patch(row._id,{ outcome:"ignored", reviewStatus:"ignored" }); return null; } });
export const attach = mutation({ args: { inboxMessageId: v.id("inboxMessages"), requestId: v.id("requests") }, handler: async (ctx,args) => { await user(ctx); const row=await ctx.db.get(args.inboxMessageId); if(!row || row.reviewStatus !== "pending") throw new Error("Entrée déjà traitée ou introuvable."); const now=Date.now(); await ctx.db.patch(row._id,{outcome:"created",reviewStatus:"attached",requestId:args.requestId}); const messageId=row.messageId ?? row.externalId; const existing=await ctx.db.query("emailMessages").withIndex("by_messageId",q=>q.eq("messageId",messageId)).unique(); if(!existing) await ctx.db.insert("emailMessages",{requestId:args.requestId,direction:"inbound",messageId,subject:row.subject,body:row.body ?? "",senderEmail:row.senderEmail,attachmentNames:row.attachmentNames,sentAt:row.receivedAt ?? now}); await ctx.db.insert("requestHistory",{requestId:args.requestId,label:"E-mail rattaché manuellement",createdAt:now}); return null; } });
export const createRequest = mutation({ args: { inboxMessageId:v.id("inboxMessages"), contactName:v.string(), contactEmail:v.optional(v.string()), contactPhone:v.optional(v.string()), organizationName:v.optional(v.string()), eventType:v.optional(v.string()), eventDate:v.optional(v.number()), eventStartTime:v.optional(v.string()), eventEndTime:v.optional(v.string()), eventAddress:v.optional(v.string()), guestCount:v.optional(v.number()), budgetCents:v.optional(v.number()), budgetPerPersonCents:v.optional(v.number()), specialNeeds:v.optional(v.string()) }, handler:async(ctx,args)=>{await user(ctx);const row=await ctx.db.get(args.inboxMessageId);if(!row||row.reviewStatus!=="pending")throw new Error("Entrée déjà traitée ou introuvable.");const now=Date.now();const requestId=await ctx.db.insert("requests",{source:"email",status:"a_qualifier",contactName:args.contactName,contactEmail:args.contactEmail,contactPhone:args.contactPhone,organizationName:args.organizationName,eventType:args.eventType,eventDate:args.eventDate,eventStartTime:args.eventStartTime,eventEndTime:args.eventEndTime,eventAddress:args.eventAddress,guestCount:args.guestCount,budgetCents:args.budgetCents,budgetPerPersonCents:args.budgetPerPersonCents,specialNeeds:args.specialNeeds,message:[row.subject?`Objet : ${row.subject}`:undefined,row.body].filter(Boolean).join("\n\n"),missingInformation:[],createdAt:now,updatedAt:now});await ctx.db.patch(row._id,{outcome:"created",reviewStatus:"created",requestId});await ctx.db.insert("emailMessages",{requestId,direction:"inbound",messageId:row.messageId??row.externalId,subject:row.subject,body:row.body??"",senderEmail:row.senderEmail,attachmentNames:row.attachmentNames,sentAt:row.receivedAt??now});await ctx.db.insert("requestHistory",{requestId,label:"Dossier créé depuis un e-mail reçu",createdAt:now});return requestId;} });
